

#include "ciNanoGui.h"

#include "NanoguiModule/nanovg/nanovg.c"
#include "NanoguiModule/nanogui/widget.cpp"
#include "NanoguiModule/nanogui/theme.cpp"
#include "NanoguiModule/nanogui/resources.cpp"
#include "NanoguiModule/nanogui/window.cpp"
#include "NanoguiModule/nanogui/screen.cpp"
#include "NanoguiModule/nanogui/label.cpp"
#include "NanoguiModule/nanogui/button.cpp"
#include "NanoguiModule/nanogui/layout.cpp"
#include "NanoguiModule/nanogui/popup.cpp"
#include "NanoguiModule/nanogui/popupbutton.cpp"
#include "NanoguiModule/nanogui/combobox.cpp"
#include "NanoguiModule/nanogui/messagedialog.cpp"
#include "NanoguiModule/nanogui/progressbar.cpp"
#include "NanoguiModule/nanogui/colorwheel.cpp"
#include "NanoguiModule/nanogui/colorpicker.cpp"
#include "NanoguiModule/nanogui/textbox.cpp"
#include "NanoguiModule/nanogui/checkbox.cpp"
#include "NanoguiModule/nanogui/graph.cpp"
#include "NanoguiModule/nanogui/imagepanel.cpp"
#include "NanoguiModule/nanogui/imageview.cpp"
#include "NanoguiModule/nanogui/vscrollpanel.cpp"
#include "NanoguiModule/nanogui/slider.cpp"
#include "NanoguiModule/util/Performance.cpp"
#include "NanoguiModule/util/NanoUtil.cpp"

